alertmanager:
  enabled: false
grafana:
  ingress:
    enabled: true
    ingressClassName: native-ic-ingress-class
    annotations:
      oci-native-ingress.oraclecloud.com/healthcheck-protocol: "HTTP"
      oci-native-ingress.oraclecloud.com/healthcheck-port: "3000"
      oci-native-ingress.oraclecloud.com/healthcheck-path: "/api/health"
      oci-native-ingress.oraclecloud.com/certificate-ocid: "ocid1.certificate.oc1.ap-tokyo-1.amaaaaaa5plvdeiavxd6vjvcxgbypmq23qeqxztqpwyw6ihuk5n6f4yer4ua"
      oci-native-ingress.oraclecloud.com/backend-tls-enabled: "false"
      oci-native-ingress.oraclecloud.com/https-listener-port: "443"
    hosts:
      - grafana.mgmt.ec-gaihan-development.com
prometheus:
  prometheusSpec:
    externalLabels:
      cluster: management
    thanos:
      image: quay.io/thanos/thanos:v0.38.0
      version: v0.38.0
      objectStorageConfig:
        secret:
          type: OCI
          config:
            provider: "instance-principal"
            bucket: "thanos-metrics-storage"
            compartment_ocid: "ocid1.compartment.oc1..aaaaaaaagmkqp2efcynmjicfgucpd4b3i6mzurw3ndfjy7my7qajy32dmhkq"
  thanosService:
    enabled: true
